<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>../assets/tts.ico</ApplicationIcon>
    <AssemblyName>TTSServer</AssemblyName>
    <Product>Portable TTS Server V2</Product>
    <Version>2.0.0</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <RuntimeFrameworkVersion>8.0.26</RuntimeFrameworkVersion>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup><PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" /></ItemGroup>
  <Target Name="ExcludeUnusedWpfReference" BeforeTargets="ResolveAssemblyReferences">
    <ItemGroup><Reference Remove="@(Reference)" Condition="$([System.String]::Copy('%(Reference.Identity)').EndsWith('Microsoft.Web.WebView2.Wpf.dll'))" /></ItemGroup>
  </Target>
</Project>
