# audio_profiles.py
"""Per-model audio processing configuration profiles."""

PROFILES = {
    "xtts": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 500,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "fish": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -40,
        "min_silence_ms": 400,
        "front_protect_ms": 80,
        "end_protect_ms": 600,
        "inter_pause_sec": 0.2,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "kokoro": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -40,
        "min_silence_ms": 300,
        "front_protect_ms": 250,
        "end_protect_ms": 1100,
        "inter_pause_sec": 0.3,
        "front_pad_sec": 0.15,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "bark": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 500,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.2,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
        "history_reset_every": 5,
    },
    "chatterbox": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "f5": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -40,
        "min_silence_ms": 400,
        "front_protect_ms": 80,
        "end_protect_ms": 600,
        "inter_pause_sec": 0.15,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "dia": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 44100,
    },
    "qwen": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "vibevoice": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "higgs": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "speecht5": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 16000,
    },
    "parler": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        # Parler's pinned mini-v1.1 runtime returns 44.1 kHz audio. Keeping
        # the native rate avoids an unnecessary lossy resample at assembly.
        "sample_rate": 44100,
    },
    "outetts": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        # The pinned OuteTTS interface exposes its decoded waveform at
        # 44.1 kHz (even though the underlying DAC asset is 24 kHz).
        # Preserve that native output instead of downsampling every job.
        "sample_rate": 44100,
    },
    "vits": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 22050,
    },
    "edge": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.2,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "voxtral": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "voxcpm2": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 48000,
    },
    "csm": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "orpheus": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
    "default": {
        "clipping": 0.95,
        "lufs": -23.0,
        "trim_db": -35,
        "min_silence_ms": 400,
        "front_protect_ms": 100,
        "end_protect_ms": 800,
        "inter_pause_sec": 0.25,
        "front_pad_sec": 0.0,
        "padding_sec": 0.5,
        "sample_rate": 24000,
    },
}

TEXT_LIMITS = {
    "xtts": 250,         # XTTS-v2 hard cap is 273 chars per generation
    "fish": 250,         # fish-speech default chunk_length is 200; 250 fits
    "kokoro": 500,       # robust on long inputs
    "bark": 200,         # caps at ~13s audio per call
    "chatterbox": 250,   # sweet spot
    "f5": 250,           # F5-TTS supports ~30s audio (~250 chars)
    "dia": 400,          # ~30s max
    "qwen": 500,         # long-context LLM (Qwen2.5-Omni-7B)
    "vibevoice": 800,    # Microsoft VibeVoice-1.5B is long-form (≤90 min)
    "higgs": 500,        # higgs-audio v2 designed for long-form narration
    "speecht5": 250,     # 600-token input limit, short audio out
    "parler": 300,       # ~30s max
    "outetts": 250,      # author's recommended sweet spot
    "vits": 250,         # short TTS, fine
    "edge": 3000,        # cloud (Microsoft Edge-TTS), API limit ~10k chars
    "voxtral": 600,      # long-form
    "voxcpm2": 400,      # ~30s max
    "csm": 300,          # conversational, short context
    "orpheus": 200,      # caps at ~14s audio per call (SNAC codec context)
    "default": 300,
}
